name: release

on:
  workflow_call:
    inputs:
      Kind:
        description: ''
        required: true
        type: string
      ResourceName:
        description: ''
        type: string
      ResourceGroupName:
        description: ''
        type: string
      BicepFile:
       description: ''
       type: string
      ParamFile:
        description: ''
        type: string
      DeployInfrastructure:
        description: ''
        type: boolean
jobs:
  deployFuncCalled:
    runs-on: self-hosted
    steps:

    - name: FunctionApp_Testing
      #if: ${{ inputs.Kind }} == FunctionApp 
      uses: ./actions/functionapp
      with:
        ResourceName: ${{inputs.ResourceName}}
        ResourceGroupName: ${{inputs.ResourceGroupName}}
        DeployInfrastructure: ${{inputs.DeployInfrastructure}}

    # - name: Deploy Bicep Infrastructure
    #   if: ${{ inputs.kind  }} == Infrastructure
    #   uses: ./actions/.github/infrastructure
    #   with:
    #     BicepFile: ${{inputs.BicepFile}}
    #     ParamFile: ${{inputs.ParamFile}}
      